const input=require("readline-sync");
let a=input.questionInt("enter the num: ");
let b=input.questionInt("enter the number: ");
c=a+b;
d=a-b;
e=a*b;
f=a/b;
g=Math.floor(a/b);
h=a%b;
console.log(c,d,e,f,g,h);